version: '3'
services:
  web:
    build: .
    volumes:
      - ./code:/var/www
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/hosts:/etc/hosts

    ports:
      - 80:80
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      APACHE_DOCUMENT_ROOT : /var/www/html/app/web
      # /var/www/html
      #/var/www/html/app/web

      #/var/www/apps/app/public/
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
   