version: '3'
services:
  web:
    build: .
    volumes:
      - ./code:/var/www/html
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/hosts:/etc/hosts

    ports:
      - 80:80
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      APACHE_DOCUMENT_ROOT : /var/www/html/web
      # /var/www/html
      #/var/www/html/app/web

      #/var/www/apps/app/public/
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      PUID: 503
      PGID: 20
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
