eduweb_training_homepage:
    path:     /
    defaults: { _controller: EduwebTrainingBundle:Default:index }

eduweb_training_registerUser:
    path: /register-user/{name}-{age}-{role}
    defaults:
        _controller: EduwebTrainingBundle:Default:registerUser
        role: user
    requirements:
        age: \d+
        role: user|admin
    methods: [GET]
eduweb_training_simple1:
    path: /simple
    defaults:
        _controller: EduwebTrainingBundle:Default:simple1

eduweb_training_simple2:
    path: /simple
    defaults:
        _controller: EduwebTrainingBundle:Default:simple2

eduweb_training_annotations:
    resource: "@EduwebTrainingBundle/Controller/"
    type: annotation

edu_web_training_aboutPage:
    path: /about
    defaults:
        _controller: EduwebTrainingBundle:Pages:about

edu_web_training_aboutJsonPage:
    path: /aboutJson
    defaults:
        _controller: EduwebTrainingBundle:Pages:aboutJson