services:
    edu_notification:
        class: Eduweb\TrainingBundle\Service\NotificationService
        arguments: ["@session"]
#    eduweb_training.example:
#        class: Eduweb\TrainingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
