parametres:
    eduweb_training.service.notification.class: Eduweb\TrainingBundle\Service\NotificationService

services:
    edu_notification:
        class: %eduweb_training.service.notification.class%
        arguments: [@session]
#    eduweb_training.example:
#        class: Eduweb\TrainingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
